import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/navbar';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} mx-auto my-0 grid min-h-screen w-11/12 max-w-[1280px] grid-rows-[auto,1fr,auto] bg-background px-12 text-white`}
      >
        <Navbar />
        <main className='min-h-[calc(100dvh-7rem)] pt-4'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
